- alias: "Power state on HA start-up"
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: "/sonoff/garage/cmnd/POWER"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "/sonoff/garage/cmnd/state"
        payload: ""