homeassistant:
  name: !secret home_name
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat
  longitude: !secret long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 14
  unit_system: metric
  time_zone: Europe/Helsinki

  # hide any raw signals used for calculation.
  customize_glob:
    "sensor.*_raw":
      hidden: true

  packages: !include_dir_named packages

frontend:
config:
http:
  base_url: !secret hass_base_url
discovery:

# Enables support for tracking state changes over time
history:
logbook:
map:
sun:

# Philips Hue
hue:
  bridges:
    - host: !secret hue_bridge_host

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password

# new ui!
lovelace:
  mode: yaml

#weather:
#  - platform: darksky
#    api_key: dbecb74a6804d24a9a23ba2de3eed196
#    mode: daily
#    units: si

sensor: !include_dir_merge_list sensors

system_health:
