homeassistant:
  name: !secret home_name
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat
  longitude: !secret long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 14
  unit_system: metric
  time_zone: Europe/Helsinki

  # set view order:
  customize:
    group.floor1:
      order: 1
    group.utomhus:
      order: 2
    group.batterier:
      order: 10

  # hide any raw signals used for calculation.
  customize_glob:
    "sensor.*_raw":
      hidden: true

  packages: !include_dir_named packages

frontend:
config:
http:
  base_url: !secret hass_base_url
discovery:

# Enables support for tracking state changes over time
history:
logbook:
map:
sun:

# Philips Hue
hue:
  bridges:
    - host: !secret hue_bridge_host

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password

group:
  utomhus:
    name: Utomhus
    view: true
    entities:
      - group.gardena
      - group.garage

  gardena:
    control: hidden
    name: Gardena
    entities:
      - sensor.gardena_temperatur
      - sensor.gardena_luftfuktighet
      - sensor.gardena_total_kortid
      - sensor.gardena_mode
      - sensor.gardena_wifi_signal
      - sensor.tid_i_status
      - sensor.gardena_status_friendly
      - sensor.gardena_batteriniva
      - sensor.gardena_spanning

sensor: !include_dir_merge_list sensors

system_health:
