homeassistant:
  customize:
    light.sonoff_garage_lights:
      friendly_name: "Garage fasadbelysning"
    sensor.sonoff_garage_temperature:
      friendly_name: "Garage temperatur"

# This forces the sonoff to expose power state on HA startup, to avoid being out of sync.
automation:
  - alias: "Power state on HA start-up"
    trigger:
      platform: homeassistant
      event: start
    action:
      - service: mqtt.publish
        data:
          topic: "/sonoff/garage/cmnd/POWER"
          payload: ""
      - service: mqtt.publish
        data:
          topic: "/sonoff/garage/cmnd/state"
          payload: ""  

  - alias: 'Tänd utebelysning vid solnedgång eller 19:00'
    trigger:
      - platform: sun
        event: sunset
      - platform: time
        at: '19:00:00'
    action:
      - service: homeassistant.turn_on
        entity_id: light.sonoff_garage_lights

  - alias: 'Släck utebelysning vid 01:00'
    trigger:
      - platform: time
        at: '01:00:00'
    action:
      - service: homeassistant.turn_off
        entity_id: light.sonoff_garage_lights

  - alias: 'Tänd utebelysning vid 06:00'
    trigger:
      - platform: time
        at: '06:00:00'
    action:
      - service: homeassistant.turn_on
        entity_id: light.sonoff_garage_lights

  - alias: 'Släck utebelysning när solen går upp eller klockan 08:45 (den som kommer senare)'
    trigger:
      - platform: sun
        event: sunrise
      - platform: time
        at: '08:45:00'
    condition:
      - condition: sun
        after: sunrise
      - condition: time
        after: '08:45:00'
    action:
      - service: homeassistant.turn_off
        entity_id: light.sonoff_garage_lights


# Garage fan
light:
  - platform: mqtt
    name: sonoff_garage_lights
    state_topic: "/sonoff/garage/stat/RESULT"
    value_template: "{{ value_json.POWER }}"
    command_topic: "/sonoff/garage/cmnd/POWER"
    availability_topic: "/sonoff/garage/tele/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false

sensor:
  # Garage temperature (vid dörren)
  - platform: mqtt
    state_topic: /sonoff/garage/tele/SENSOR
    name: sonoff_garage_temperature
    unit_of_measurement: "°C"
    icon: mdi:thermometer
    value_template: "{{ value_json['DS18B20'].Temperature }}"
    expire_after: !secret mqtt_timeout
    force_update: true

# Robot area switch.
switch:
  - platform: command_line
    switches:
      robot_area_cmd:
        command_on: '/usr/bin/curl -X GET http://10.0.1.62/control\?cmd\=gpio,5,1'
        command_off: '/usr/bin/curl -X GET http://10.0.1.62/control\?cmd\=gpio,5,0'
        command_state: '/usr/bin/curl -X GET http://10.0.1.62/json'
        value_template: '{{ value_json["Sensors"][2]["robotarea"] == 1 }}'
        friendly_name: "Robot Area (1 == runt hus, 0 == runt garage)"